name: stable

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ["2.5", "2.6", "2.7", "3.0", "jruby-9.2.14.0"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Get sqlite for Rails test projects
        run: sudo apt-get install libsqlite3-dev

      - name: Run tests (MRI)
        run: bundle exec rake
        if: "!startsWith(matrix.ruby, 'jruby')"

      - name: Run tests (JRuby)
        run: JRUBY_OPTS=--debug bundle exec rake
        if: startsWith(matrix.ruby, 'jruby')

      - name: Merge coverage
        run: bundle exec ruby scripts/merge_coverage
        if: matrix.ruby == '3.0'
